### ISSUE TITLE
Missed title of articles and cann't not parse URL from ted.com ?

### ISSUE THREAD

**Issue by dproton** [DZamataev/DZReadability#1]
Thank for your contribution. I tried example project and observe that the string after parse missed title the of articles. I also tried ted.com but it cann't parsed.
Have a nice day !

**Comment by DZamataev** [comment]
Hi! Thanks for your attention, the project is pretty young and not yet fully functional. There are few issues after porting GGReadabilityParser from using NSXMLDocument parser to GDataXML-HTML parser, including not all the options work as expected and sometimes GDataXML-HTML parser crashes. I am going to solve them till the end of October.
Title of the article should be preserved if you do not specify `GGReadabilityParserOptionRemoveHeader`. This option is enabled in demo project by default.

**Comment by dproton** [comment]
Thank for your reply !

**Comment by DZamataev** [comment]
@dproton Hello!
I've rolled a huge update (0.2.0), please pay attention to it.
It contains many improvements and the whole project is stable now.
I tried this article http://blog.ted.com/2015/01/08/ted-community-news-in-brief-1-8-2015/ and it parses all good.

**Comment by dproton** [comment]
Thank for your contribution, @DZamataev !
Have a nice day !
